/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fb",
        "on-secondary-fixed-variant": "#423f7f",
        "error": "#ba1a1a",
        "secondary-fixed": "#e3dfff",
        "surface-variant": "#e1e2e4",
        "inverse-primary": "#c4c0ff",
        "primary-fixed": "#e3dfff",
        "surface-container-low": "#f3f4f6",
        "primary-container": "#5b4fe8",
        "on-tertiary-container": "#ffe2d3",
        "on-surface-variant": "#464555",
        "surface-dim": "#d9dadc",
        "on-secondary-container": "#494585",
        "on-tertiary-fixed-variant": "#763300",
        "background": "#f8f9fb",
        "tertiary-fixed": "#ffdbca",
        "on-primary-fixed-variant": "#3824c7",
        "surface-tint": "#5244de",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#161051",
        "on-error-container": "#93000a",
        "surface-container": "#edeef0",
        "outline": "#777586",
        "primary": "#4231cf",
        "on-tertiary-fixed": "#331200",
        "secondary": "#5a5798",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#c8c4d8",
        "surface-container-highest": "#e1e2e4",
        "surface": "#f8f9fb",
        "on-primary-container": "#e8e4ff",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8ea",
        "primary-fixed-dim": "#c4c0ff",
        "tertiary": "#843a00",
        "secondary-container": "#bbb7ff",
        "inverse-on-surface": "#f0f1f3",
        "tertiary-container": "#aa4c00",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#120068",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c4c0ff",
        "tertiary-fixed-dim": "#ffb68e",
        "on-surface": "#191c1e",
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Inter'", "sans-serif"],
        "label": ["'Inter'", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out both',
        'slide-up': 'slideUp 0.4s ease-out both',
        'slide-down': 'slideDown 0.3s ease-out both',
        'scale-in': 'scaleIn 0.3s ease-out both',
        'spin-slow': 'spin 1.2s linear infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'toast-in': 'toastIn 0.35s ease-out both',
        'toast-out': 'toastOut 0.3s ease-in both',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        toastIn: {
          '0%': { opacity: '0', transform: 'translateX(60px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        toastOut: {
          '0%': { opacity: '1', transform: 'translateX(0)' },
          '100%': { opacity: '0', transform: 'translateX(60px)' },
        },
      },
      transitionTimingFunction: {
        'bounce-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}